name: holy_quran
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8

  # কোর ফাংশনালিটি (Adhan, Location, Time)
  adhan: ^2.0.0+1
  geolocator: ^13.0.2
  intl: ^0.19.0
  http: ^1.2.2

  # লোকাল ডাটাবেস ও স্টোরেজ
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.3.5

  # অডিও এবং স্টেট ম্যানেজমেন্ট
  just_audio: ^0.9.42
  provider: ^6.1.2
  connectivity_plus: ^6.1.0

  # নোটিফিকেশন সার্ভিস
  # নোট: আমি লেটেস্ট স্ট্যাবল ভার্সন ১৭.২.২ রেখেছি, ২১.০.০ ভার্সনটি অনেক সময় কম্পাটিবিলিটি ইস্যু করে
  flutter_local_notifications: ^17.2.2

  # শেয়ারিং ও ইউটিলিটি ফিচার
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  flutter_dotenv: ^5.2.1
  in_app_review: ^2.0.9
  package_info_plus: ^8.1.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/final_background.jpg
    - assets/images/bismillah.png
    - assets/images/compass_dial.png
    - assets/images/qibla_needle.png
    - assets/images/surah_icon_image.png

    # JSON Data Files
    - assets/data/quran_arabic.json
    - assets/data/en_quran.json
    - assets/data/bn_quran.json
    - assets/data/es_quran.json
    - assets/data/fr_quran.json
    - assets/data/id_quran.json
    - assets/data/ru_quran.json
    - assets/data/sv_quran.json
    - assets/data/tr_quran.json
    - assets/data/ur_quran.json
    - assets/data/zh_quran.json

    # Sounds
    - assets/sounds/click.ogg
    - assets/sounds/complete.wav

  fonts:
    - family: QuranFont
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf

    - family: Translation
      fonts:
        - asset: assets/fonts/Roboto-bold.ttf